//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel_App.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBANKA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLBANKA()
        {
            this.TBLBANKAHAREKET = new HashSet<TBLBANKAHAREKET>();
        }
    
        public int BANKAID { get; set; }
        public string SUBE { get; set; }
        public string BANKADI { get; set; }
        public string BANKAHESAPNO { get; set; }
        public Nullable<int> KUR { get; set; }
        public Nullable<int> DURUM { get; set; }
    
        public virtual TBLDURUM TBLDURUM { get; set; }
        public virtual TBLKURLAR TBLKURLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBANKAHAREKET> TBLBANKAHAREKET { get; set; }
    }
}
