//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel_App.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCARI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLCARI()
        {
            this.TBLCARIHAREKET = new HashSet<TBLCARIHAREKET>();
            this.TBLCARIKONUKHAREKET = new HashSet<TBLCARIKONUKHAREKET>();
            this.TBLREZERVASYON = new HashSet<TBLREZERVASYON>();
        }
    
        public int CARIID { get; set; }
        public string CARIADSOYAD { get; set; }
        public string CARIADRES { get; set; }
        public string CARITC { get; set; }
        public string VERGIDAIRE { get; set; }
        public string TELEFON { get; set; }
        public string MAIL { get; set; }
        public string KIMLIKFOTO1 { get; set; }
        public string KIMLIKFOTO2 { get; set; }
        public Nullable<int> CARITUR { get; set; }
        public string YETKILI { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<int> UYRUK { get; set; }
        public Nullable<decimal> BAKIYE { get; set; }
        public Nullable<int> DURUM { get; set; }
    
        public virtual TBLCARITUR TBLCARITUR { get; set; }
        public virtual TBLDURUM TBLDURUM { get; set; }
        public virtual TBLUYRUK TBLUYRUK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCARIHAREKET> TBLCARIHAREKET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCARIKONUKHAREKET> TBLCARIKONUKHAREKET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLREZERVASYON> TBLREZERVASYON { get; set; }
    }
}
