//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel_App.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCARIHAREKET
    {
        public int CARIHAREKETID { get; set; }
        public Nullable<int> CARIID { get; set; }
        public Nullable<int> ISLEM { get; set; }
        public string BELGENO { get; set; }
        public Nullable<int> KUR { get; set; }
        public Nullable<decimal> NAKIT { get; set; }
        public Nullable<decimal> KREDIKARTI { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<int> PERSONEL { get; set; }
        public Nullable<int> DURUM { get; set; }
    
        public virtual TBLCARI TBLCARI { get; set; }
        public virtual TBLDURUM TBLDURUM { get; set; }
        public virtual TBLISLEM TBLISLEM { get; set; }
        public virtual TBLKURLAR TBLKURLAR { get; set; }
        public virtual TBLPERSONEL TBLPERSONEL { get; set; }
    }
}
