//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel_App.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKURLAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLKURLAR()
        {
            this.TBLBANKA = new HashSet<TBLBANKA>();
            this.TBLCARIHAREKET = new HashSet<TBLCARIHAREKET>();
        }
    
        public int KURID { get; set; }
        public string KURAD { get; set; }
        public string KURSEMBOL { get; set; }
        public Nullable<decimal> KURDEGER { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<int> DURUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBANKA> TBLBANKA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCARIHAREKET> TBLCARIHAREKET { get; set; }
        public virtual TBLDURUM TBLDURUM { get; set; }
        public virtual TBLDURUM TBLDURUM1 { get; set; }
    }
}
